ttfautohint '/Finished/ttf/Bodoni-96-Book.ttf' '/Finished/ttf hints/Bodoni-96-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-96-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Medium.ttf' '/Finished/ttf hints/Bodoni-96-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-96-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Bold.ttf' '/Finished/ttf hints/Bodoni-96-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-96-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Fatface.ttf' '/Finished/ttf hints/Bodoni-96-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-96-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-96-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Book.ttf' '/Finished/ttf hints/Bodoni-72-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-72-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Medium.ttf' '/Finished/ttf hints/Bodoni-72-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-72-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Bold.ttf' '/Finished/ttf hints/Bodoni-72-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-72-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Fatface.ttf' '/Finished/ttf hints/Bodoni-72-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-72-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-72-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Book.ttf' '/Finished/ttf hints/Bodoni-48-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-48-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Medium.ttf' '/Finished/ttf hints/Bodoni-48-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-48-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Bold.ttf' '/Finished/ttf hints/Bodoni-48-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-48-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Fatface.ttf' '/Finished/ttf hints/Bodoni-48-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-48-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-48-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Book.ttf' '/Finished/ttf hints/Bodoni-36-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-36-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Medium.ttf' '/Finished/ttf hints/Bodoni-36-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-36-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Bold.ttf' '/Finished/ttf hints/Bodoni-36-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-36-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Fatface.ttf' '/Finished/ttf hints/Bodoni-36-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-36-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-36-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Book.ttf' '/Finished/ttf hints/Bodoni-24-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-24-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Medium.ttf' '/Finished/ttf hints/Bodoni-24-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-24-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Bold.ttf' '/Finished/ttf hints/Bodoni-24-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-24-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Fatface.ttf' '/Finished/ttf hints/Bodoni-24-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-24-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-24-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Book.ttf' '/Finished/ttf hints/Bodoni-16-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-16-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Medium.ttf' '/Finished/ttf hints/Bodoni-16-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-16-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Bold.ttf' '/Finished/ttf hints/Bodoni-16-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-16-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Fatface.ttf' '/Finished/ttf hints/Bodoni-16-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-16-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-16-Fatface-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Book.ttf' '/Finished/ttf hints/Bodoni-11-Book.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Book-Italic.ttf' '/Finished/ttf hints/Bodoni-11-Book-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Medium.ttf' '/Finished/ttf hints/Bodoni-11-Medium.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Medium-Italic.ttf' '/Finished/ttf hints/Bodoni-11-Medium-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Bold.ttf' '/Finished/ttf hints/Bodoni-11-Bold.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Bold-Italic.ttf' '/Finished/ttf hints/Bodoni-11-Bold-Italic.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Fatface.ttf' '/Finished/ttf hints/Bodoni-11-Fatface.ttf' &&
ttfautohint '/Finished/ttf/Bodoni-11-Fatface-Italic.ttf' '/Finished/ttf hints/Bodoni-11-Fatface-Italic.ttf'
